# Generated by Django 4.2.2 on 2024-03-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='longDescription',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='الوصف الكامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='smallDescription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='وصف قصير'),
        ),
    ]
