# Generated by Django 4.2.2 on 2024-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_smalldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='longDescription',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='الوصف الكامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='smallDescription',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='وصف قصير'),
        ),
    ]
