# Generated by Django 4.2.2 on 2024-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_longdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True, verbose_name='اسم المنتج متوافق'),
        ),
    ]
